### 회원가입
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "haj",
  "email": "haj@example.com",
  "password": "12345678"
}

###

### 로그인
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "haj@example.com",
  "password": "12345678"
}

###

### 레시피 생성
POST http://localhost:3000/api/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

{
  "title": "블랙 밀크티",
  "content": "블랙티 150ml,우유 90ml넣고 스팀, 과당 0%",
  "type": "dessert",
  "difficulty": "easy",
  "cookingTime": 1
}

###

### 전체 레시피 조회
GET http://localhost:3000/api/recipes

###

### 북마크 추가
POST http://localhost:3000/api/recipes/683724d95139df30535951d8/bookmark
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

###

### 사용자 북마크 목록
GET http://localhost:3000/api/users/me/bookmarks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

### 레시피 수정
PUT http://localhost:3000/api/recipes/68393e349b231b8c15b89d80
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

{
   "title": "New title",
  "ingredients": "Egg, Milk",
  "instructions": "Mix and bake"
}
 
### 레시피 삭제
DELETE http://localhost:3000/api/recipes/68393e349b231b8c15b89d80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

### 내가 쓴 레시피 조회
GET http://localhost:3000/api/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

### 북마크 삭제
DELETE http://localhost:3000/api/recipes/683724d95139df30535951d8/bookmark
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODUwMzMzOCwiZXhwIjoxNzQ4NTA2OTM4fQ.ro-TlRp10wvYfhrJ5BLh-DUsuQ9M2cW6CDF430BW684

### 레시피 검색 테스트
GET http://localhost:3000/api/recipes/search?keyword=김치
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

### 필터링 테스트1: korean + easy + 30분 이하
GET http://localhost:3000/api/recipes/filter?difficulty=easy&type=korean&cookingTime=under30
Content-Type: application/json

### 필터링 테스트2: dessert + easy + 10분 이하
GET http://localhost:3000/api/recipes/filter?difficulty=easy&type=dessert&cookingTime=under10
Content-Type: application/json

### 필터링 테스트3: western만 필터링
GET http://localhost:3000/api/recipes/filter?type=western
Content-Type: application/json

### 댓글 작성 (로그인 필요)
POST http://localhost:3000/api/comments/683724d95139df30535951d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

{
  "content": "잘 보고 갑니다람쥐"
}

### 댓글 조회
GET http://localhost:3000/api/comments/683724d95139df30535951d8

### 댓글 수정
PUT http://localhost:3000/api/comments/68393ed59b231b8c15b89d86
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k

{
  "content": "잘 보고 갑니다"
}

### 댓글 삭제
DELETE http://localhost:3000/api/comments/68393ed59b231b8c15b89d86
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODM3MjM2NzUxMzlkZjMwNTM1OTUxZDMiLCJlbWFpbCI6ImhhakBleGFtcGxlLmNvbSIsImlhdCI6MTc0ODU4MTQ5NSwiZXhwIjoxNzQ4NTg1MDk1fQ.4wFz4uj-D-tLIBb_sMSgWLeOlzd5gTLA6Ixo8l5hj_k